name: Publish to S3 Bucket

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Build React App
        uses: leiteszeke/front-app-to-s3@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clean Folder
        run: |
          aws s3 rm s3://aws-actions-deploy --recursive

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync build/ s3://aws-actions-deploy --acl public-read

      - name: Invalidate Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_DISTRIBUTION_ID }} --paths "/*"
